using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Vapor.Vsl.SourceGenerator
{
    /// <summary>
    /// Emits a formatter for every type taking part in VSL serialization.
    /// </summary>
    /// <remarks>
    /// The generated formatter is nested inside the type, which is what lets it read and write
    /// private <c>[SerializeField]</c> members directly instead of through
    /// <c>FieldInfo.GetValue</c>. It must produce output byte-identical to the reflection path —
    /// the two are covered by a differential test for exactly that reason.
    /// </remarks>
    [Generator]
    public sealed class VslIncrementalGenerator : IIncrementalGenerator
    {
        private const string Ns = "global::Vapor.Serialization";
        private const string FormatterName = "VslGeneratedFormatter";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // A type qualifies either by carrying [VslSerializable] itself, or by holding a member
            // marked [VslSerialize].
            var fromTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
                VslModelBuilder.SerializableAttribute,
                static (node, _) => node is TypeDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol);

            var fromMembers = context.SyntaxProvider.ForAttributeWithMetadataName(
                VslModelBuilder.SerializeAttribute,
                static (node, _) => node is VariableDeclaratorSyntax or PropertyDeclarationSyntax or FieldDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol.ContainingType);

            var candidates = fromTypes.Collect()
                .Combine(fromMembers.Collect())
                .Combine(context.CompilationProvider.Select(static (compilation, _) => compilation.AssemblyName));

            context.RegisterSourceOutput(candidates, static (spc, input) =>
                Execute(spc, input.Left.Left, input.Left.Right, input.Right));
        }

        private static void Execute(
            SourceProductionContext context,
            ImmutableArray<INamedTypeSymbol> fromTypes,
            ImmutableArray<INamedTypeSymbol> fromMembers,
            string assemblyName)
        {
            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            var ordered = new List<INamedTypeSymbol>();

            foreach (var type in fromTypes.Concat(fromMembers))
            {
                if (type != null && seen.Add(type))
                {
                    ordered.Add(type);
                }
            }

            var registrations = new List<string>();

            foreach (var type in ordered)
            {
                var model = VslModelBuilder.Build(type, context);
                if (model == null)
                {
                    continue;
                }

                context.AddSource($"{model.HintName}.Vsl.g.cs", SourceText.From(Emit(model), Encoding.UTF8));
                registrations.Add($"{model.TypeName}.{FormatterName}.Instance");
            }

            if (registrations.Count > 0)
            {
                context.AddSource("VslGeneratedRegistrar.g.cs",
                    SourceText.From(EmitRegistrar(registrations, assemblyName), Encoding.UTF8));
            }
        }

        #region Emit

        private static string Emit(VslTypeModel model)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();

            var indent = 0;

            if (model.Namespace != null)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
                indent++;
            }

            foreach (var containing in model.ContainingTypes)
            {
                sb.AppendLine($"{Pad(indent)}{containing}");
                sb.AppendLine($"{Pad(indent)}{{");
                indent++;
            }

            sb.AppendLine($"{Pad(indent)}partial {model.TypeKeyword} {model.SimpleName}");
            sb.AppendLine($"{Pad(indent)}{{");
            indent++;

            EmitFormatter(sb, model, indent);

            indent--;
            sb.AppendLine($"{Pad(indent)}}}");

            foreach (var _ in model.ContainingTypes)
            {
                indent--;
                sb.AppendLine($"{Pad(indent)}}}");
            }

            if (model.Namespace != null)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void EmitFormatter(StringBuilder sb, VslTypeModel model, int indent)
        {
            var pad = Pad(indent);
            var inner = Pad(indent + 1);
            var body = Pad(indent + 2);
            var deep = Pad(indent + 3);

            sb.AppendLine($"{pad}/// <summary>Generated VSL formatter. Nested so it can reach this type's private members.</summary>");
            sb.AppendLine($"{pad}public sealed class {FormatterName} : {Ns}.VslFormatter<{model.TypeName}>");
            sb.AppendLine($"{pad}{{");
            sb.AppendLine($"{inner}public static readonly {FormatterName} Instance = new {FormatterName}();");
            sb.AppendLine();
            sb.AppendLine($"{inner}private int _allScalar;");
            sb.AppendLine();

            // --- PrefersInline ---
            sb.AppendLine($"{inner}private bool PrefersInline({Ns}.VslContext context)");
            sb.AppendLine($"{inner}{{");
            if (model.Members.Count == 0)
            {
                sb.AppendLine($"{body}return false;");
            }
            else
            {
                sb.AppendLine($"{body}if ({model.Members.Count} > context.Options.InlineMemberLimit) return false;");
                sb.AppendLine($"{body}if (_allScalar == 0)");
                sb.AppendLine($"{body}{{");
                var scalarChecks = string.Join(
                    $" &&{System.Environment.NewLine}{deep}    ",
                    model.Members.Select(m => $"{Ns}.VslFormatterRegistry.Get<{m.TypeName}>().IsScalar"));
                sb.AppendLine($"{deep}_allScalar = ({scalarChecks}) ? 1 : 2;");
                sb.AppendLine($"{body}}}");
                sb.AppendLine();
                sb.AppendLine($"{body}return _allScalar == 1;");
            }

            sb.AppendLine($"{inner}}}");
            sb.AppendLine();

            // --- Write ---
            sb.AppendLine($"{inner}public override void Write(ref {Ns}.VslWriter writer, in {model.TypeName} value, {Ns}.VslContext context)");
            sb.AppendLine($"{inner}{{");

            if (!model.IsValueType)
            {
                sb.AppendLine($"{body}if (value is null) {{ writer.WriteNull(); return; }}");
                sb.AppendLine();
            }

            if (!model.IsSealedOrValueType)
            {
                sb.AppendLine($"{body}// A derived instance in a base-typed slot is tagged and handed to its own formatter.");
                sb.AppendLine($"{body}var __runtimeType = value.GetType();");
                sb.AppendLine($"{body}if (__runtimeType != typeof({model.TypeName}))");
                sb.AppendLine($"{body}{{");
                sb.AppendLine($"{deep}writer.WriteTypeTag({Ns}.VslTypeRegistry.GetTag(__runtimeType));");
                sb.AppendLine($"{deep}{Ns}.VslFormatterRegistry.Get(__runtimeType).WriteObject(ref writer, value, context);");
                sb.AppendLine($"{deep}return;");
                sb.AppendLine($"{body}}}");
                sb.AppendLine();
            }

            sb.AppendLine($"{body}context.EnterDepth();");
            sb.AppendLine($"{body}try");
            sb.AppendLine($"{body}{{");
            sb.AppendLine($"{deep}writer.BeginObject(PrefersInline(context));");

            foreach (var member in model.Members)
            {
                if (!string.IsNullOrEmpty(member.Comment))
                {
                    sb.AppendLine($"{deep}writer.WriteComment({Literal(member.Comment)});");
                }

                sb.AppendLine($"{deep}writer.WriteMember({Literal(member.VslName)});");
                sb.AppendLine($"{deep}{Ns}.VslFormatterRegistry.Get<{member.TypeName}>().Write(ref writer, value.{member.Access}, context);");
            }

            sb.AppendLine($"{deep}writer.EndObject();");
            sb.AppendLine($"{body}}}");
            sb.AppendLine($"{body}finally");
            sb.AppendLine($"{body}{{");
            sb.AppendLine($"{deep}context.ExitDepth();");
            sb.AppendLine($"{body}}}");
            sb.AppendLine($"{inner}}}");
            sb.AppendLine();

            // --- Read ---
            sb.AppendLine($"{inner}public override {model.TypeName} Read(ref {Ns}.VslReader reader, {Ns}.VslContext context)");
            sb.AppendLine($"{inner}{{");
            sb.AppendLine($"{body}if (reader.TryReadNull()) return default;");
            sb.AppendLine();

            if (!model.IsSealedOrValueType)
            {
                sb.AppendLine($"{body}if (reader.TryReadTypeTag(out var __tag))");
                sb.AppendLine($"{body}{{");
                sb.AppendLine($"{deep}var __concrete = {Ns}.VslTypeRegistry.Resolve(__tag, typeof({model.TypeName}));");
                sb.AppendLine($"{deep}if (__concrete != null && __concrete != typeof({model.TypeName}))");
                sb.AppendLine($"{deep}{{");
                sb.AppendLine($"{deep}    return ({model.TypeName}){Ns}.VslFormatterRegistry.Get(__concrete).ReadObject(ref reader, context);");
                sb.AppendLine($"{deep}}}");
                sb.AppendLine($"{body}}}");
                sb.AppendLine();
            }
            else
            {
                sb.AppendLine($"{body}reader.TryReadTypeTag(out _);");
                sb.AppendLine();
            }

            sb.AppendLine($"{body}var value = new {model.TypeName}();");
            sb.AppendLine($"{body}context.EnterDepth();");
            sb.AppendLine($"{body}try");
            sb.AppendLine($"{body}{{");
            sb.AppendLine($"{deep}reader.ReadObjectStart();");
            sb.AppendLine($"{deep}while (reader.TryReadMemberName(out var __name))");
            sb.AppendLine($"{deep}{{");

            var first = true;
            foreach (var member in model.Members)
            {
                var keyword = first ? "if" : "else if";
                first = false;
                sb.AppendLine($"{deep}    {keyword} ({Ns}.VslNames.Matches(__name, {Literal(member.VslName)}))");
                sb.AppendLine($"{deep}    {{");
                sb.AppendLine($"{deep}        value.{member.Access} = {Ns}.VslFormatterRegistry.Get<{member.TypeName}>().Read(ref reader, context);");
                sb.AppendLine($"{deep}    }}");
            }

            if (!first)
            {
                sb.AppendLine($"{deep}    else");
                sb.AppendLine($"{deep}    {{");
            }

            sb.AppendLine($"{deep}        if (context.Options.Strict)");
            sb.AppendLine($"{deep}        {{");
            sb.AppendLine($"{deep}            throw new {Ns}.VslException(\"'\" + __name.ToString() + \"' is not a serialized member of {model.SimpleName}.\");");
            sb.AppendLine($"{deep}        }}");
            sb.AppendLine();
            sb.AppendLine($"{deep}        reader.SkipValue();");

            if (!first)
            {
                sb.AppendLine($"{deep}    }}");
            }

            sb.AppendLine($"{deep}}}");
            sb.AppendLine($"{body}}}");
            sb.AppendLine($"{body}finally");
            sb.AppendLine($"{body}{{");
            sb.AppendLine($"{deep}context.ExitDepth();");
            sb.AppendLine($"{body}}}");
            sb.AppendLine();
            sb.AppendLine($"{body}return value;");
            sb.AppendLine($"{inner}}}");

            sb.AppendLine($"{pad}}}");
        }

        /// <summary>
        /// Registers every generated formatter for this assembly on domain load, so lookups find the
        /// generated one rather than falling through to reflection.
        /// </summary>
        private static string EmitRegistrar(List<string> registrations, string assemblyName)
        {
            var suffix = Sanitize(assemblyName);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();
            sb.AppendLine("namespace Vapor.Serialization.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    internal static class VslGeneratedRegistrar_{suffix}");
            sb.AppendLine("    {");
            // Deliberately the older attribute pair rather than [OnCodeInitializing]. Unity decides
            // whether an assembly references Unity.Analyzers.Common by looking for lifecycle attributes
            // in source, which happens before this generator contributes any. An assembly whose only
            // lifecycle method is this one therefore fails to reference it and the callback never runs —
            // silently, taking every formatter in that assembly with it. That would land on any consumer
            // with VSL types, in their assembly, with no obvious cause and no fix they own.
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("        [global::UnityEditor.InitializeOnLoadMethod]");
            sb.AppendLine("#endif");
            sb.AppendLine("        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("        internal static void Register()");
            sb.AppendLine("        {");

            foreach (var registration in registrations)
            {
                sb.AppendLine($"            global::Vapor.Serialization.VslFormatterRegistry.Register({registration});");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        #endregion

        private static string Pad(int indent) => new string(' ', indent * 4);

        private static string Literal(string value) =>
            value == null ? "null" : "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r") + "\"";

        private static string Sanitize(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return "Assembly";
            }

            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            }

            return sb.ToString();
        }
    }
}
