//This file is auto-generated by the Vapor Editor [DataRegistryMenu.GenerateGameplayTagCategoriesFile]. Do not modify directly.
using System;

namespace Vapor.GameplayTags
{
    public enum GameplayTagDefaultCategories
    {
        Socket,
        AnimationLayer,
        Movement,
        Event,
        Input,
        Cue,
        Addressable,
        Montage,
        Attribute,
        Effect,
        Ability,
        Items,
        Entity,
        Loot,
        GameplayTagData,
        Item,
        Weather,
        World,
        Rune,
        Trait,
        Damage,
        Stance,
        Monster,
        Npc,
        Structure,
        City,
        Mine,
        Guild,
        Enchant,
        Sim,
        Agent,
        Ui,
        State,
        Ai,
        Terrain,
        Vapor,
        Spell,
        Resist,
        Training,
        Skill,
        Focus,
        Enchantment,
        Progression,
        Scatter,
        Biome,
        WorldSettings,
        Subsystems,
        Actors,
        Camp,
    }

    public static class GameplayTagCategories
    {
        public const string SOCKET = "Socket";
        public const string ANIMATION_LAYER = "AnimationLayer";
        public const string MOVEMENT = "Movement";
        public const string EVENT = "Event";
        public const string INPUT = "Input";
        public const string CUE = "Cue";
        public const string ADDRESSABLE = "Addressable";
        public const string MONTAGE = "Montage";
        public const string ATTRIBUTE = "Attribute";
        public const string EFFECT = "Effect";
        public const string ABILITY = "Ability";
        public const string ITEMS = "Items";
        public const string ENTITY = "Entity";
        public const string LOOT = "Loot";
        public const string GAMEPLAY_TAG_DATA = "GameplayTagData";
        public const string ITEM = "Item";
        public const string WEATHER = "Weather";
        public const string WORLD = "World";
        public const string RUNE = "Rune";
        public const string TRAIT = "Trait";
        public const string DAMAGE = "Damage";
        public const string STANCE = "Stance";
        public const string MONSTER = "Monster";
        public const string NPC = "Npc";
        public const string STRUCTURE = "Structure";
        public const string CITY = "City";
        public const string MINE = "Mine";
        public const string GUILD = "Guild";
        public const string ENCHANT = "Enchant";
        public const string SIM = "Sim";
        public const string AGENT = "Agent";
        public const string UI = "Ui";
        public const string STATE = "State";
        public const string AI = "Ai";
        public const string TERRAIN = "Terrain";
        public const string VAPOR = "Vapor";
        public const string SPELL = "Spell";
        public const string RESIST = "Resist";
        public const string TRAINING = "Training";
        public const string SKILL = "Skill";
        public const string FOCUS = "Focus";
        public const string ENCHANTMENT = "Enchantment";
        public const string PROGRESSION = "Progression";
        public const string SCATTER = "Scatter";
        public const string BIOME = "Biome";
        public const string WORLD_SETTINGS = "WorldSettings";
        public const string SUBSYSTEMS = "Subsystems";
        public const string ACTORS = "Actors";
        public const string CAMP = "Camp";

        public static string GetNameForCategory(GameplayTagDefaultCategories category)
        {
            return category switch
            {
                GameplayTagDefaultCategories.Socket => SOCKET,
                GameplayTagDefaultCategories.AnimationLayer => ANIMATION_LAYER,
                GameplayTagDefaultCategories.Movement => MOVEMENT,
                GameplayTagDefaultCategories.Event => EVENT,
                GameplayTagDefaultCategories.Input => INPUT,
                GameplayTagDefaultCategories.Cue => CUE,
                GameplayTagDefaultCategories.Addressable => ADDRESSABLE,
                GameplayTagDefaultCategories.Montage => MONTAGE,
                GameplayTagDefaultCategories.Attribute => ATTRIBUTE,
                GameplayTagDefaultCategories.Effect => EFFECT,
                GameplayTagDefaultCategories.Ability => ABILITY,
                GameplayTagDefaultCategories.Items => ITEMS,
                GameplayTagDefaultCategories.Entity => ENTITY,
                GameplayTagDefaultCategories.Loot => LOOT,
                GameplayTagDefaultCategories.GameplayTagData => GAMEPLAY_TAG_DATA,
                GameplayTagDefaultCategories.Item => ITEM,
                GameplayTagDefaultCategories.Weather => WEATHER,
                GameplayTagDefaultCategories.World => WORLD,
                GameplayTagDefaultCategories.Rune => RUNE,
                GameplayTagDefaultCategories.Trait => TRAIT,
                GameplayTagDefaultCategories.Damage => DAMAGE,
                GameplayTagDefaultCategories.Stance => STANCE,
                GameplayTagDefaultCategories.Monster => MONSTER,
                GameplayTagDefaultCategories.Npc => NPC,
                GameplayTagDefaultCategories.Structure => STRUCTURE,
                GameplayTagDefaultCategories.City => CITY,
                GameplayTagDefaultCategories.Mine => MINE,
                GameplayTagDefaultCategories.Guild => GUILD,
                GameplayTagDefaultCategories.Enchant => ENCHANT,
                GameplayTagDefaultCategories.Sim => SIM,
                GameplayTagDefaultCategories.Agent => AGENT,
                GameplayTagDefaultCategories.Ui => UI,
                GameplayTagDefaultCategories.State => STATE,
                GameplayTagDefaultCategories.Ai => AI,
                GameplayTagDefaultCategories.Terrain => TERRAIN,
                GameplayTagDefaultCategories.Vapor => VAPOR,
                GameplayTagDefaultCategories.Spell => SPELL,
                GameplayTagDefaultCategories.Resist => RESIST,
                GameplayTagDefaultCategories.Training => TRAINING,
                GameplayTagDefaultCategories.Skill => SKILL,
                GameplayTagDefaultCategories.Focus => FOCUS,
                GameplayTagDefaultCategories.Enchantment => ENCHANTMENT,
                GameplayTagDefaultCategories.Progression => PROGRESSION,
                GameplayTagDefaultCategories.Scatter => SCATTER,
                GameplayTagDefaultCategories.Biome => BIOME,
                GameplayTagDefaultCategories.WorldSettings => WORLD_SETTINGS,
                GameplayTagDefaultCategories.Subsystems => SUBSYSTEMS,
                GameplayTagDefaultCategories.Actors => ACTORS,
                GameplayTagDefaultCategories.Camp => CAMP,
                _ => throw new ArgumentOutOfRangeException(nameof(category), category, null)
            };
        }
    }
}
