//This file is auto-generated by the Vapor Editor [DataRegistryMenu.GenerateGameplayTagCategoriesFile]. Do not modify directly.
using System;

namespace Vapor.GameplayTags
{
    public enum GameplayTagDefaultCategories
    {
        Socket,
        AnimationLayer,
        Movement,
        Event,
        Input,
        Cue,
        Addressable,
        Montage,
        Attribute,
        Effect,
        Ability,
        Items,
        Entity,
        Loot,
        GameplayTagData,
        Item,
        Vapor,
        WorldSettings,
        Subsystems,
        Actors,
        Room,
        Ship,
        Station,
    }

    public static class GameplayTagCategories
    {
        public const string SOCKET = "Socket";
        public const string ANIMATION_LAYER = "AnimationLayer";
        public const string MOVEMENT = "Movement";
        public const string EVENT = "Event";
        public const string INPUT = "Input";
        public const string CUE = "Cue";
        public const string ADDRESSABLE = "Addressable";
        public const string MONTAGE = "Montage";
        public const string ATTRIBUTE = "Attribute";
        public const string EFFECT = "Effect";
        public const string ABILITY = "Ability";
        public const string ITEMS = "Items";
        public const string ENTITY = "Entity";
        public const string LOOT = "Loot";
        public const string GAMEPLAY_TAG_DATA = "GameplayTagData";
        public const string ITEM = "Item";
        public const string VAPOR = "Vapor";
        public const string WORLD_SETTINGS = "WorldSettings";
        public const string SUBSYSTEMS = "Subsystems";
        public const string ACTORS = "Actors";
        public const string ROOM = "Room";
        public const string SHIP = "Ship";
        public const string STATION = "Station";

        public static string GetNameForCategory(GameplayTagDefaultCategories category)
        {
            return category switch
            {
                GameplayTagDefaultCategories.Socket => SOCKET,
                GameplayTagDefaultCategories.AnimationLayer => ANIMATION_LAYER,
                GameplayTagDefaultCategories.Movement => MOVEMENT,
                GameplayTagDefaultCategories.Event => EVENT,
                GameplayTagDefaultCategories.Input => INPUT,
                GameplayTagDefaultCategories.Cue => CUE,
                GameplayTagDefaultCategories.Addressable => ADDRESSABLE,
                GameplayTagDefaultCategories.Montage => MONTAGE,
                GameplayTagDefaultCategories.Attribute => ATTRIBUTE,
                GameplayTagDefaultCategories.Effect => EFFECT,
                GameplayTagDefaultCategories.Ability => ABILITY,
                GameplayTagDefaultCategories.Items => ITEMS,
                GameplayTagDefaultCategories.Entity => ENTITY,
                GameplayTagDefaultCategories.Loot => LOOT,
                GameplayTagDefaultCategories.GameplayTagData => GAMEPLAY_TAG_DATA,
                GameplayTagDefaultCategories.Item => ITEM,
                GameplayTagDefaultCategories.Vapor => VAPOR,
                GameplayTagDefaultCategories.WorldSettings => WORLD_SETTINGS,
                GameplayTagDefaultCategories.Subsystems => SUBSYSTEMS,
                GameplayTagDefaultCategories.Actors => ACTORS,
                GameplayTagDefaultCategories.Room => ROOM,
                GameplayTagDefaultCategories.Ship => SHIP,
                GameplayTagDefaultCategories.Station => STATION,
                _ => throw new ArgumentOutOfRangeException(nameof(category), category, null)
            };
        }
    }
}
