using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Vapor.Rpc.SourceGenerator
{
    /// <summary>
    /// Writes the send path, the receive handler, and the registration for every <c>[VaporRpc]</c>
    /// method on a <c>VaporNetworkObject</c>.
    /// </summary>
    /// <remarks>
    /// The author declares the rpc as a partial method with no body and puts the body in a second
    /// partial named <c>&lt;Name&gt;_Implementation</c>. This generator supplies the other half of
    /// each: the implementing half of the rpc — serialize the arguments, send to the targets the
    /// attribute names, then fall through into the implementation when this peer is one of those
    /// targets — and the declaring half of <c>_Implementation</c>, which is what makes a missing body
    /// a compile error rather than a call that quietly does nothing.
    /// </remarks>
    [Generator]
    public sealed class VaporRpcIncrementalGenerator : IIncrementalGenerator
    {
        private const string NetworkObject = "global::Vapor.NetworkObjects.VaporNetworkObject";
        private const string FastBufferReader = "global::Unity.Netcode.FastBufferReader";
        private const string RegistrarName = "RegisterVaporRpcs";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var rpcs = context.SyntaxProvider.ForAttributeWithMetadataName(
                VaporRpcModelBuilder.RpcAttribute,
                static (node, _) => node is MethodDeclarationSyntax,
                static (ctx, _) => (
                    Method: ctx.TargetSymbol as IMethodSymbol,
                    Attribute: ctx.Attributes.FirstOrDefault()));

            var input = rpcs.Collect().Combine(context.CompilationProvider);

            context.RegisterSourceOutput(input, static (spc, values) =>
                Execute(spc, values.Left, values.Right));
        }

        private static void Execute(
            SourceProductionContext context,
            ImmutableArray<(IMethodSymbol Method, AttributeData Attribute)> rpcs,
            Compilation compilation)
        {
            if (rpcs.IsDefaultOrEmpty)
            {
                return;
            }

            var known = RpcKnownSymbols.Resolve(compilation);
            if (known.NetworkObject == null)
            {
                // Nothing in this assembly can be a network object, so [VaporRpc] here cannot mean
                // what it says. VRPC001 would fire on every one of them; staying quiet is kinder.
                return;
            }

            // Grouped by declaring type: one generated partial per type holds that type's send paths,
            // receive handlers, and the single registration entry point Unity calls.
            var byType = new Dictionary<INamedTypeSymbol, List<(IMethodSymbol Method, AttributeData Attribute)>>(SymbolEqualityComparer.Default);
            var order = new List<INamedTypeSymbol>();

            foreach (var rpc in rpcs)
            {
                if (rpc.Method == null || rpc.Attribute == null)
                {
                    continue;
                }

                var type = rpc.Method.ContainingType;
                if (!byType.TryGetValue(type, out var methods))
                {
                    methods = new List<(IMethodSymbol, AttributeData)>();
                    byType.Add(type, methods);
                    order.Add(type);
                }

                methods.Add(rpc);
            }

            foreach (var type in order)
            {
                if (!VaporRpcModelBuilder.IsPartialEverywhere(type))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        VaporRpcDiagnostics.TypeNotPartial,
                        type.Locations.FirstOrDefault() ?? Location.None,
                        type.ToDisplayString()));
                    continue;
                }

                var model = VaporRpcModelBuilder.BuildType(type);

                foreach (var (method, attribute) in byType[type])
                {
                    var built = VaporRpcModelBuilder.BuildMethod(method, attribute, known, compilation.AssemblyName, context);
                    if (built != null)
                    {
                        model.Methods.Add(built);
                    }
                }

                if (model.Methods.Count > 0)
                {
                    context.AddSource($"{model.HintName}.VaporRpc.g.cs", SourceText.From(Emit(model), Encoding.UTF8));
                }
            }
        }

        #region Emit

        private static string Emit(RpcTypeModel model)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine();

            var indent = 0;

            if (model.Namespace != null)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
                indent++;
            }

            foreach (var containing in model.ContainingTypes)
            {
                sb.AppendLine($"{Pad(indent)}{containing}");
                sb.AppendLine($"{Pad(indent)}{{");
                indent++;
            }

            sb.AppendLine($"{Pad(indent)}partial {model.TypeKeyword} {model.SimpleName}");
            sb.AppendLine($"{Pad(indent)}{{");
            indent++;

            foreach (var method in model.Methods)
            {
                EmitSend(sb, model, method, indent);
                sb.AppendLine();
                EmitImplementationDeclaration(sb, method, indent);
                sb.AppendLine();
                EmitReceive(sb, model, method, indent);
                sb.AppendLine();
            }

            EmitRegistrar(sb, model, indent);

            indent--;
            sb.AppendLine($"{Pad(indent)}}}");

            foreach (var _ in model.ContainingTypes)
            {
                indent--;
                sb.AppendLine($"{Pad(indent)}}}");
            }

            if (model.Namespace != null)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// The implementing half of the author's declaration: serialize, send, and run the body here
        /// too when this peer is one of the targets.
        /// </summary>
        private static void EmitSend(StringBuilder sb, RpcTypeModel model, RpcMethodModel method, int indent)
        {
            var pad = Pad(indent);
            var body = Pad(indent + 1);
            var deep = Pad(indent + 2);

            sb.AppendLine($"{pad}/// <summary>");
            sb.AppendLine($"{pad}/// Sends <c>{method.Name}</c> to <c>{Escape(Unqualify(method.SendTo))}</c>, then runs");
            sb.AppendLine($"{pad}/// <see cref=\"{method.ImplementationName}\"/> here when this peer is one of its targets.");
            sb.AppendLine($"{pad}/// </summary>");

            // Tells Netcode's IL post-processor to generate serialization for the argument types that
            // travel through NetworkVariableSerialization<T>. It scans every method in the assembly
            // for this, so declaring it here is enough — nothing else in the project need mention
            // these types.
            foreach (var serializationType in method.SerializationTypes)
            {
                sb.AppendLine($"{pad}[global::Unity.Netcode.GenerateSerializationForType(typeof({serializationType}))]");
            }

            sb.AppendLine($"{pad}{method.Modifiers} partial void {method.Name}({method.ParameterList})");
            sb.AppendLine($"{pad}{{");
            sb.AppendLine($"{body}if (!BeginSendRpc(0x{method.Hash:X8}u, out var {method.WriterLocal}))");
            sb.AppendLine($"{body}{{");
            sb.AppendLine($"{deep}return;");
            sb.AppendLine($"{body}}}");

            if (method.Parameters.Count > 0)
            {
                sb.AppendLine();
                foreach (var parameter in method.Parameters)
                {
                    sb.AppendLine($"{body}{parameter.WriteCall}({method.WriterLocal}, {parameter.Name});");
                }
            }

            sb.AppendLine();
            sb.AppendLine($"{body}if (!EndSendRpc({method.WriterLocal}, {method.SendTo}, {method.NetworkDelivery}))");
            sb.AppendLine($"{body}{{");
            sb.AppendLine($"{deep}return;");
            sb.AppendLine($"{body}}}");
            sb.AppendLine();
            sb.AppendLine($"{body}{method.ImplementationName}({method.ArgumentList});");
            sb.AppendLine($"{pad}}}");
        }

        /// <summary>
        /// The declaring half of the body method. Declared with an explicit accessibility on purpose:
        /// that is what makes the compiler demand an implementation, so an rpc whose body was never
        /// written fails to build instead of silently doing nothing on arrival.
        /// </summary>
        private static void EmitImplementationDeclaration(StringBuilder sb, RpcMethodModel method, int indent)
        {
            var pad = Pad(indent);

            sb.AppendLine($"{pad}/// <summary>");
            sb.AppendLine($"{pad}/// Runs <c>{method.Name}</c>. Write this half yourself — it is the body of the rpc, and it");
            sb.AppendLine($"{pad}/// runs on every peer the rpc reached, including this one when it is a target.");
            sb.AppendLine($"{pad}/// </summary>");
            sb.AppendLine($"{pad}private partial void {method.ImplementationName}({method.ParameterList});");
        }

        /// <summary>
        /// Deserializes the arguments and calls the body. Registered against the rpc id, so a derived
        /// instance dispatches to the type that declared the rpc.
        /// </summary>
        private static void EmitReceive(StringBuilder sb, RpcTypeModel model, RpcMethodModel method, int indent)
        {
            var pad = Pad(indent);
            var body = Pad(indent + 1);

            sb.AppendLine($"{pad}/// <summary>Reads <c>{method.Name}</c>'s arguments off the wire and runs its body.</summary>");
            sb.AppendLine($"{pad}private static void {method.ReceiveName}({NetworkObject} rpcTarget, {FastBufferReader} rpcReader)");
            sb.AppendLine($"{pad}{{");

            foreach (var parameter in method.Parameters)
            {
                sb.AppendLine($"{body}var {parameter.Local} = {parameter.ReadCast}{parameter.ReadCall}(rpcReader);");
            }

            var arguments = string.Join(", ", method.Parameters.Select(p => p.Local));
            sb.AppendLine($"{body}(({model.TypeName})rpcTarget).{method.ImplementationName}({arguments});");
            sb.AppendLine($"{pad}}}");
        }

        /// <summary>
        /// Registration lives inside the type rather than in one per-assembly class, so every member
        /// it touches can stay private and a private or nested rpc type needs no special handling.
        /// </summary>
        private static void EmitRegistrar(StringBuilder sb, RpcTypeModel model, int indent)
        {
            var pad = Pad(indent);
            var body = Pad(indent + 1);

            sb.AppendLine($"{pad}/// <summary>Puts {model.SimpleName}'s rpcs in the receive table before any of them can arrive.</summary>");
            // Deliberately the older attribute pair rather than [OnCodeInitializing]: see the note in the
            // VSL generator. Unity resolves the Unity.Analyzers.Common reference from lifecycle attributes
            // present in source, before a generator contributes any, so an assembly whose only lifecycle
            // method is generated never gets the reference and the registration silently does not run.
            sb.AppendLine($"{pad}[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine($"{pad}[global::UnityEditor.InitializeOnLoadMethod]");
            sb.AppendLine("#endif");
            sb.AppendLine($"{pad}private static void {RegistrarName}()");
            sb.AppendLine($"{pad}{{");

            foreach (var method in model.Methods)
            {
                sb.AppendLine($"{body}RegisterRpc(0x{method.Hash:X8}u, {method.ReceiveName}, \"{method.DisplayName}\");");
            }

            sb.AppendLine($"{pad}}}");
        }

        #endregion

        private static string Pad(int indent) => new string(' ', indent * 4);

        private static string Escape(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

        /// <summary>
        /// "global::Unity.Netcode.SendTo.Server" reads as "SendTo.Server" in a doc comment.
        /// </summary>
        private static string Unqualify(string value)
        {
            var parts = value.Split('.');
            return parts.Length < 2 ? value : $"{parts[parts.Length - 2]}.{parts[parts.Length - 1]}";
        }
    }
}
